/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActuationsRouteImport } from './routes/actuations'
import { Route as AdapterRouteImport } from './routes/adapter'
import { Route as AdaptersRouteImport } from './routes/adapters'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as CanbusRouteImport } from './routes/canbus'
import { Route as CodesRouteImport } from './routes/codes'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ConnectionRouteImport } from './routes/connection'
import { Route as CoverageRouteImport } from './routes/coverage'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as DeepScanRouteImport } from './routes/deep-scan'
import { Route as DiagnosticSessionsRouteImport } from './routes/diagnostic-sessions'
import { Route as DiagnosticTestsRouteImport } from './routes/diagnostic-tests'
import { Route as DtcAnalysisRouteImport } from './routes/dtc-analysis'
import { Route as EmissionsRouteImport } from './routes/emissions'
import { Route as EvRouteImport } from './routes/ev'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as EvidenceRecorderRouteImport } from './routes/evidence-recorder'
import { Route as ExpertRouteImport } from './routes/expert'
import { Route as FreezeFrameRouteImport } from './routes/freeze-frame'
import { Route as FullScanRouteImport } from './routes/full-scan'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as GraphsRouteImport } from './routes/graphs'
import { Route as GuidedDiagnosticsRouteImport } from './routes/guided-diagnostics'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LocalAgentRouteImport } from './routes/local-agent'
import { Route as MeasurementsRouteImport } from './routes/measurements'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as RepairComparisonRouteImport } from './routes/repair-comparison'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ScopeRouteImport } from './routes/scope'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as ServiceFunctionsRouteImport } from './routes/service-functions'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TopologyRouteImport } from './routes/topology'
import { Route as TuningRouteImport } from './routes/tuning'
import { Route as VehicleRouteImport } from './routes/vehicle'
import { Route as VehicleIdentificationRouteImport } from './routes/vehicle-identification'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActuationsRoute = ActuationsRouteImport.update({
  id: '/actuations',
  path: '/actuations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdapterRoute = AdapterRouteImport.update({
  id: '/adapter',
  path: '/adapter',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptersRoute = AdaptersRouteImport.update({
  id: '/adapters',
  path: '/adapters',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CanbusRoute = CanbusRouteImport.update({
  id: '/canbus',
  path: '/canbus',
  getParentRoute: () => rootRouteImport,
} as any)
const CodesRoute = CodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionRoute = ConnectionRouteImport.update({
  id: '/connection',
  path: '/connection',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverageRoute = CoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepScanRoute = DeepScanRouteImport.update({
  id: '/deep-scan',
  path: '/deep-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticSessionsRoute = DiagnosticSessionsRouteImport.update({
  id: '/diagnostic-sessions',
  path: '/diagnostic-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticTestsRoute = DiagnosticTestsRouteImport.update({
  id: '/diagnostic-tests',
  path: '/diagnostic-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const DtcAnalysisRoute = DtcAnalysisRouteImport.update({
  id: '/dtc-analysis',
  path: '/dtc-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const EmissionsRoute = EmissionsRouteImport.update({
  id: '/emissions',
  path: '/emissions',
  getParentRoute: () => rootRouteImport,
} as any)
const EvRoute = EvRouteImport.update({
  id: '/ev',
  path: '/ev',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRecorderRoute = EvidenceRecorderRouteImport.update({
  id: '/evidence-recorder',
  path: '/evidence-recorder',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertRoute = ExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => rootRouteImport,
} as any)
const FreezeFrameRoute = FreezeFrameRouteImport.update({
  id: '/freeze-frame',
  path: '/freeze-frame',
  getParentRoute: () => rootRouteImport,
} as any)
const FullScanRoute = FullScanRouteImport.update({
  id: '/full-scan',
  path: '/full-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphsRoute = GraphsRouteImport.update({
  id: '/graphs',
  path: '/graphs',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidedDiagnosticsRoute = GuidedDiagnosticsRouteImport.update({
  id: '/guided-diagnostics',
  path: '/guided-diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalAgentRoute = LocalAgentRouteImport.update({
  id: '/local-agent',
  path: '/local-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasurementsRoute = MeasurementsRouteImport.update({
  id: '/measurements',
  path: '/measurements',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairComparisonRoute = RepairComparisonRouteImport.update({
  id: '/repair-comparison',
  path: '/repair-comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeRoute = ScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceFunctionsRoute = ServiceFunctionsRouteImport.update({
  id: '/service-functions',
  path: '/service-functions',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TopologyRoute = TopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => rootRouteImport,
} as any)
const TuningRoute = TuningRouteImport.update({
  id: '/tuning',
  path: '/tuning',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleRoute = VehicleRouteImport.update({
  id: '/vehicle',
  path: '/vehicle',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleIdentificationRoute = VehicleIdentificationRouteImport.update({
  id: '/vehicle-identification',
  path: '/vehicle-identification',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actuations': typeof ActuationsRoute
  '/adapter': typeof AdapterRoute
  '/adapters': typeof AdaptersRoute
  '/audit': typeof AuditRoute
  '/canbus': typeof CanbusRoute
  '/codes': typeof CodesRoute
  '/compare': typeof CompareRoute
  '/connection': typeof ConnectionRoute
  '/coverage': typeof CoverageRoute
  '/data-sources': typeof DataSourcesRoute
  '/deep-scan': typeof DeepScanRoute
  '/diagnostic-sessions': typeof DiagnosticSessionsRoute
  '/diagnostic-tests': typeof DiagnosticTestsRoute
  '/dtc-analysis': typeof DtcAnalysisRoute
  '/emissions': typeof EmissionsRoute
  '/ev': typeof EvRoute
  '/evidence': typeof EvidenceRoute
  '/evidence-recorder': typeof EvidenceRecorderRoute
  '/expert': typeof ExpertRoute
  '/freeze-frame': typeof FreezeFrameRoute
  '/full-scan': typeof FullScanRoute
  '/garage': typeof GarageRoute
  '/graphs': typeof GraphsRoute
  '/guided-diagnostics': typeof GuidedDiagnosticsRoute
  '/health': typeof HealthRoute
  '/local-agent': typeof LocalAgentRoute
  '/measurements': typeof MeasurementsRoute
  '/performance': typeof PerformanceRoute
  '/plugins': typeof PluginsRoute
  '/repair-comparison': typeof RepairComparisonRoute
  '/reports': typeof ReportsRoute
  '/safety': typeof SafetyRoute
  '/scope': typeof ScopeRoute
  '/security': typeof SecurityRoute
  '/service': typeof ServiceRoute
  '/service-functions': typeof ServiceFunctionsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/topology': typeof TopologyRoute
  '/tuning': typeof TuningRoute
  '/vehicle': typeof VehicleRoute
  '/vehicle-identification': typeof VehicleIdentificationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actuations': typeof ActuationsRoute
  '/adapter': typeof AdapterRoute
  '/adapters': typeof AdaptersRoute
  '/audit': typeof AuditRoute
  '/canbus': typeof CanbusRoute
  '/codes': typeof CodesRoute
  '/compare': typeof CompareRoute
  '/connection': typeof ConnectionRoute
  '/coverage': typeof CoverageRoute
  '/data-sources': typeof DataSourcesRoute
  '/deep-scan': typeof DeepScanRoute
  '/diagnostic-sessions': typeof DiagnosticSessionsRoute
  '/diagnostic-tests': typeof DiagnosticTestsRoute
  '/dtc-analysis': typeof DtcAnalysisRoute
  '/emissions': typeof EmissionsRoute
  '/ev': typeof EvRoute
  '/evidence': typeof EvidenceRoute
  '/evidence-recorder': typeof EvidenceRecorderRoute
  '/expert': typeof ExpertRoute
  '/freeze-frame': typeof FreezeFrameRoute
  '/full-scan': typeof FullScanRoute
  '/garage': typeof GarageRoute
  '/graphs': typeof GraphsRoute
  '/guided-diagnostics': typeof GuidedDiagnosticsRoute
  '/health': typeof HealthRoute
  '/local-agent': typeof LocalAgentRoute
  '/measurements': typeof MeasurementsRoute
  '/performance': typeof PerformanceRoute
  '/plugins': typeof PluginsRoute
  '/repair-comparison': typeof RepairComparisonRoute
  '/reports': typeof ReportsRoute
  '/safety': typeof SafetyRoute
  '/scope': typeof ScopeRoute
  '/security': typeof SecurityRoute
  '/service': typeof ServiceRoute
  '/service-functions': typeof ServiceFunctionsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/topology': typeof TopologyRoute
  '/tuning': typeof TuningRoute
  '/vehicle': typeof VehicleRoute
  '/vehicle-identification': typeof VehicleIdentificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actuations': typeof ActuationsRoute
  '/adapter': typeof AdapterRoute
  '/adapters': typeof AdaptersRoute
  '/audit': typeof AuditRoute
  '/canbus': typeof CanbusRoute
  '/codes': typeof CodesRoute
  '/compare': typeof CompareRoute
  '/connection': typeof ConnectionRoute
  '/coverage': typeof CoverageRoute
  '/data-sources': typeof DataSourcesRoute
  '/deep-scan': typeof DeepScanRoute
  '/diagnostic-sessions': typeof DiagnosticSessionsRoute
  '/diagnostic-tests': typeof DiagnosticTestsRoute
  '/dtc-analysis': typeof DtcAnalysisRoute
  '/emissions': typeof EmissionsRoute
  '/ev': typeof EvRoute
  '/evidence': typeof EvidenceRoute
  '/evidence-recorder': typeof EvidenceRecorderRoute
  '/expert': typeof ExpertRoute
  '/freeze-frame': typeof FreezeFrameRoute
  '/full-scan': typeof FullScanRoute
  '/garage': typeof GarageRoute
  '/graphs': typeof GraphsRoute
  '/guided-diagnostics': typeof GuidedDiagnosticsRoute
  '/health': typeof HealthRoute
  '/local-agent': typeof LocalAgentRoute
  '/measurements': typeof MeasurementsRoute
  '/performance': typeof PerformanceRoute
  '/plugins': typeof PluginsRoute
  '/repair-comparison': typeof RepairComparisonRoute
  '/reports': typeof ReportsRoute
  '/safety': typeof SafetyRoute
  '/scope': typeof ScopeRoute
  '/security': typeof SecurityRoute
  '/service': typeof ServiceRoute
  '/service-functions': typeof ServiceFunctionsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/topology': typeof TopologyRoute
  '/tuning': typeof TuningRoute
  '/vehicle': typeof VehicleRoute
  '/vehicle-identification': typeof VehicleIdentificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actuations'
    | '/adapter'
    | '/adapters'
    | '/audit'
    | '/canbus'
    | '/codes'
    | '/compare'
    | '/connection'
    | '/coverage'
    | '/data-sources'
    | '/deep-scan'
    | '/diagnostic-sessions'
    | '/diagnostic-tests'
    | '/dtc-analysis'
    | '/emissions'
    | '/ev'
    | '/evidence'
    | '/evidence-recorder'
    | '/expert'
    | '/freeze-frame'
    | '/full-scan'
    | '/garage'
    | '/graphs'
    | '/guided-diagnostics'
    | '/health'
    | '/local-agent'
    | '/measurements'
    | '/performance'
    | '/plugins'
    | '/repair-comparison'
    | '/reports'
    | '/safety'
    | '/scope'
    | '/security'
    | '/service'
    | '/service-functions'
    | '/sessions'
    | '/settings'
    | '/topology'
    | '/tuning'
    | '/vehicle'
    | '/vehicle-identification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actuations'
    | '/adapter'
    | '/adapters'
    | '/audit'
    | '/canbus'
    | '/codes'
    | '/compare'
    | '/connection'
    | '/coverage'
    | '/data-sources'
    | '/deep-scan'
    | '/diagnostic-sessions'
    | '/diagnostic-tests'
    | '/dtc-analysis'
    | '/emissions'
    | '/ev'
    | '/evidence'
    | '/evidence-recorder'
    | '/expert'
    | '/freeze-frame'
    | '/full-scan'
    | '/garage'
    | '/graphs'
    | '/guided-diagnostics'
    | '/health'
    | '/local-agent'
    | '/measurements'
    | '/performance'
    | '/plugins'
    | '/repair-comparison'
    | '/reports'
    | '/safety'
    | '/scope'
    | '/security'
    | '/service'
    | '/service-functions'
    | '/sessions'
    | '/settings'
    | '/topology'
    | '/tuning'
    | '/vehicle'
    | '/vehicle-identification'
  id:
    | '__root__'
    | '/'
    | '/actuations'
    | '/adapter'
    | '/adapters'
    | '/audit'
    | '/canbus'
    | '/codes'
    | '/compare'
    | '/connection'
    | '/coverage'
    | '/data-sources'
    | '/deep-scan'
    | '/diagnostic-sessions'
    | '/diagnostic-tests'
    | '/dtc-analysis'
    | '/emissions'
    | '/ev'
    | '/evidence'
    | '/evidence-recorder'
    | '/expert'
    | '/freeze-frame'
    | '/full-scan'
    | '/garage'
    | '/graphs'
    | '/guided-diagnostics'
    | '/health'
    | '/local-agent'
    | '/measurements'
    | '/performance'
    | '/plugins'
    | '/repair-comparison'
    | '/reports'
    | '/safety'
    | '/scope'
    | '/security'
    | '/service'
    | '/service-functions'
    | '/sessions'
    | '/settings'
    | '/topology'
    | '/tuning'
    | '/vehicle'
    | '/vehicle-identification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActuationsRoute: typeof ActuationsRoute
  AdapterRoute: typeof AdapterRoute
  AdaptersRoute: typeof AdaptersRoute
  AuditRoute: typeof AuditRoute
  CanbusRoute: typeof CanbusRoute
  CodesRoute: typeof CodesRoute
  CompareRoute: typeof CompareRoute
  ConnectionRoute: typeof ConnectionRoute
  CoverageRoute: typeof CoverageRoute
  DataSourcesRoute: typeof DataSourcesRoute
  DeepScanRoute: typeof DeepScanRoute
  DiagnosticSessionsRoute: typeof DiagnosticSessionsRoute
  DiagnosticTestsRoute: typeof DiagnosticTestsRoute
  DtcAnalysisRoute: typeof DtcAnalysisRoute
  EmissionsRoute: typeof EmissionsRoute
  EvRoute: typeof EvRoute
  EvidenceRoute: typeof EvidenceRoute
  EvidenceRecorderRoute: typeof EvidenceRecorderRoute
  ExpertRoute: typeof ExpertRoute
  FreezeFrameRoute: typeof FreezeFrameRoute
  FullScanRoute: typeof FullScanRoute
  GarageRoute: typeof GarageRoute
  GraphsRoute: typeof GraphsRoute
  GuidedDiagnosticsRoute: typeof GuidedDiagnosticsRoute
  HealthRoute: typeof HealthRoute
  LocalAgentRoute: typeof LocalAgentRoute
  MeasurementsRoute: typeof MeasurementsRoute
  PerformanceRoute: typeof PerformanceRoute
  PluginsRoute: typeof PluginsRoute
  RepairComparisonRoute: typeof RepairComparisonRoute
  ReportsRoute: typeof ReportsRoute
  SafetyRoute: typeof SafetyRoute
  ScopeRoute: typeof ScopeRoute
  SecurityRoute: typeof SecurityRoute
  ServiceRoute: typeof ServiceRoute
  ServiceFunctionsRoute: typeof ServiceFunctionsRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  TopologyRoute: typeof TopologyRoute
  TuningRoute: typeof TuningRoute
  VehicleRoute: typeof VehicleRoute
  VehicleIdentificationRoute: typeof VehicleIdentificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actuations': {
      id: '/actuations'
      path: '/actuations'
      fullPath: '/actuations'
      preLoaderRoute: typeof ActuationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adapter': {
      id: '/adapter'
      path: '/adapter'
      fullPath: '/adapter'
      preLoaderRoute: typeof AdapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adapters': {
      id: '/adapters'
      path: '/adapters'
      fullPath: '/adapters'
      preLoaderRoute: typeof AdaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canbus': {
      id: '/canbus'
      path: '/canbus'
      fullPath: '/canbus'
      preLoaderRoute: typeof CanbusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codes': {
      id: '/codes'
      path: '/codes'
      fullPath: '/codes'
      preLoaderRoute: typeof CodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connection': {
      id: '/connection'
      path: '/connection'
      fullPath: '/connection'
      preLoaderRoute: typeof ConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coverage': {
      id: '/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof CoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep-scan': {
      id: '/deep-scan'
      path: '/deep-scan'
      fullPath: '/deep-scan'
      preLoaderRoute: typeof DeepScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic-sessions': {
      id: '/diagnostic-sessions'
      path: '/diagnostic-sessions'
      fullPath: '/diagnostic-sessions'
      preLoaderRoute: typeof DiagnosticSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic-tests': {
      id: '/diagnostic-tests'
      path: '/diagnostic-tests'
      fullPath: '/diagnostic-tests'
      preLoaderRoute: typeof DiagnosticTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dtc-analysis': {
      id: '/dtc-analysis'
      path: '/dtc-analysis'
      fullPath: '/dtc-analysis'
      preLoaderRoute: typeof DtcAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emissions': {
      id: '/emissions'
      path: '/emissions'
      fullPath: '/emissions'
      preLoaderRoute: typeof EmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ev': {
      id: '/ev'
      path: '/ev'
      fullPath: '/ev'
      preLoaderRoute: typeof EvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence-recorder': {
      id: '/evidence-recorder'
      path: '/evidence-recorder'
      fullPath: '/evidence-recorder'
      preLoaderRoute: typeof EvidenceRecorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert': {
      id: '/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof ExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freeze-frame': {
      id: '/freeze-frame'
      path: '/freeze-frame'
      fullPath: '/freeze-frame'
      preLoaderRoute: typeof FreezeFrameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/full-scan': {
      id: '/full-scan'
      path: '/full-scan'
      fullPath: '/full-scan'
      preLoaderRoute: typeof FullScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphs': {
      id: '/graphs'
      path: '/graphs'
      fullPath: '/graphs'
      preLoaderRoute: typeof GraphsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guided-diagnostics': {
      id: '/guided-diagnostics'
      path: '/guided-diagnostics'
      fullPath: '/guided-diagnostics'
      preLoaderRoute: typeof GuidedDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-agent': {
      id: '/local-agent'
      path: '/local-agent'
      fullPath: '/local-agent'
      preLoaderRoute: typeof LocalAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measurements': {
      id: '/measurements'
      path: '/measurements'
      fullPath: '/measurements'
      preLoaderRoute: typeof MeasurementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair-comparison': {
      id: '/repair-comparison'
      path: '/repair-comparison'
      fullPath: '/repair-comparison'
      preLoaderRoute: typeof RepairComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope': {
      id: '/scope'
      path: '/scope'
      fullPath: '/scope'
      preLoaderRoute: typeof ScopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-functions': {
      id: '/service-functions'
      path: '/service-functions'
      fullPath: '/service-functions'
      preLoaderRoute: typeof ServiceFunctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topology': {
      id: '/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof TopologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuning': {
      id: '/tuning'
      path: '/tuning'
      fullPath: '/tuning'
      preLoaderRoute: typeof TuningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle': {
      id: '/vehicle'
      path: '/vehicle'
      fullPath: '/vehicle'
      preLoaderRoute: typeof VehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-identification': {
      id: '/vehicle-identification'
      path: '/vehicle-identification'
      fullPath: '/vehicle-identification'
      preLoaderRoute: typeof VehicleIdentificationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActuationsRoute: ActuationsRoute,
  AdapterRoute: AdapterRoute,
  AdaptersRoute: AdaptersRoute,
  AuditRoute: AuditRoute,
  CanbusRoute: CanbusRoute,
  CodesRoute: CodesRoute,
  CompareRoute: CompareRoute,
  ConnectionRoute: ConnectionRoute,
  CoverageRoute: CoverageRoute,
  DataSourcesRoute: DataSourcesRoute,
  DeepScanRoute: DeepScanRoute,
  DiagnosticSessionsRoute: DiagnosticSessionsRoute,
  DiagnosticTestsRoute: DiagnosticTestsRoute,
  DtcAnalysisRoute: DtcAnalysisRoute,
  EmissionsRoute: EmissionsRoute,
  EvRoute: EvRoute,
  EvidenceRoute: EvidenceRoute,
  EvidenceRecorderRoute: EvidenceRecorderRoute,
  ExpertRoute: ExpertRoute,
  FreezeFrameRoute: FreezeFrameRoute,
  FullScanRoute: FullScanRoute,
  GarageRoute: GarageRoute,
  GraphsRoute: GraphsRoute,
  GuidedDiagnosticsRoute: GuidedDiagnosticsRoute,
  HealthRoute: HealthRoute,
  LocalAgentRoute: LocalAgentRoute,
  MeasurementsRoute: MeasurementsRoute,
  PerformanceRoute: PerformanceRoute,
  PluginsRoute: PluginsRoute,
  RepairComparisonRoute: RepairComparisonRoute,
  ReportsRoute: ReportsRoute,
  SafetyRoute: SafetyRoute,
  ScopeRoute: ScopeRoute,
  SecurityRoute: SecurityRoute,
  ServiceRoute: ServiceRoute,
  ServiceFunctionsRoute: ServiceFunctionsRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  TopologyRoute: TopologyRoute,
  TuningRoute: TuningRoute,
  VehicleRoute: VehicleRoute,
  VehicleIdentificationRoute: VehicleIdentificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
