/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActuationsRouteImport } from './routes/actuations'
import { Route as AdaptersRouteImport } from './routes/adapters'
import { Route as CanbusRouteImport } from './routes/canbus'
import { Route as CodesRouteImport } from './routes/codes'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as DeepScanRouteImport } from './routes/deep-scan'
import { Route as EmissionsRouteImport } from './routes/emissions'
import { Route as EvRouteImport } from './routes/ev'
import { Route as ExpertRouteImport } from './routes/expert'
import { Route as FreezeFrameRouteImport } from './routes/freeze-frame'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as HealthRouteImport } from './routes/health'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TuningRouteImport } from './routes/tuning'
import { Route as VehicleRouteImport } from './routes/vehicle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActuationsRoute = ActuationsRouteImport.update({
  id: '/actuations',
  path: '/actuations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptersRoute = AdaptersRouteImport.update({
  id: '/adapters',
  path: '/adapters',
  getParentRoute: () => rootRouteImport,
} as any)
const CanbusRoute = CanbusRouteImport.update({
  id: '/canbus',
  path: '/canbus',
  getParentRoute: () => rootRouteImport,
} as any)
const CodesRoute = CodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepScanRoute = DeepScanRouteImport.update({
  id: '/deep-scan',
  path: '/deep-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const EmissionsRoute = EmissionsRouteImport.update({
  id: '/emissions',
  path: '/emissions',
  getParentRoute: () => rootRouteImport,
} as any)
const EvRoute = EvRouteImport.update({
  id: '/ev',
  path: '/ev',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertRoute = ExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => rootRouteImport,
} as any)
const FreezeFrameRoute = FreezeFrameRouteImport.update({
  id: '/freeze-frame',
  path: '/freeze-frame',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TuningRoute = TuningRouteImport.update({
  id: '/tuning',
  path: '/tuning',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleRoute = VehicleRouteImport.update({
  id: '/vehicle',
  path: '/vehicle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actuations': typeof ActuationsRoute
  '/adapters': typeof AdaptersRoute
  '/canbus': typeof CanbusRoute
  '/codes': typeof CodesRoute
  '/compare': typeof CompareRoute
  '/data-sources': typeof DataSourcesRoute
  '/deep-scan': typeof DeepScanRoute
  '/emissions': typeof EmissionsRoute
  '/ev': typeof EvRoute
  '/expert': typeof ExpertRoute
  '/freeze-frame': typeof FreezeFrameRoute
  '/garage': typeof GarageRoute
  '/health': typeof HealthRoute
  '/performance': typeof PerformanceRoute
  '/reports': typeof ReportsRoute
  '/safety': typeof SafetyRoute
  '/security': typeof SecurityRoute
  '/service': typeof ServiceRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/tuning': typeof TuningRoute
  '/vehicle': typeof VehicleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actuations': typeof ActuationsRoute
  '/adapters': typeof AdaptersRoute
  '/canbus': typeof CanbusRoute
  '/codes': typeof CodesRoute
  '/compare': typeof CompareRoute
  '/data-sources': typeof DataSourcesRoute
  '/deep-scan': typeof DeepScanRoute
  '/emissions': typeof EmissionsRoute
  '/ev': typeof EvRoute
  '/expert': typeof ExpertRoute
  '/freeze-frame': typeof FreezeFrameRoute
  '/garage': typeof GarageRoute
  '/health': typeof HealthRoute
  '/performance': typeof PerformanceRoute
  '/reports': typeof ReportsRoute
  '/safety': typeof SafetyRoute
  '/security': typeof SecurityRoute
  '/service': typeof ServiceRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/tuning': typeof TuningRoute
  '/vehicle': typeof VehicleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actuations': typeof ActuationsRoute
  '/adapters': typeof AdaptersRoute
  '/canbus': typeof CanbusRoute
  '/codes': typeof CodesRoute
  '/compare': typeof CompareRoute
  '/data-sources': typeof DataSourcesRoute
  '/deep-scan': typeof DeepScanRoute
  '/emissions': typeof EmissionsRoute
  '/ev': typeof EvRoute
  '/expert': typeof ExpertRoute
  '/freeze-frame': typeof FreezeFrameRoute
  '/garage': typeof GarageRoute
  '/health': typeof HealthRoute
  '/performance': typeof PerformanceRoute
  '/reports': typeof ReportsRoute
  '/safety': typeof SafetyRoute
  '/security': typeof SecurityRoute
  '/service': typeof ServiceRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/tuning': typeof TuningRoute
  '/vehicle': typeof VehicleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actuations'
    | '/adapters'
    | '/canbus'
    | '/codes'
    | '/compare'
    | '/data-sources'
    | '/deep-scan'
    | '/emissions'
    | '/ev'
    | '/expert'
    | '/freeze-frame'
    | '/garage'
    | '/health'
    | '/performance'
    | '/reports'
    | '/safety'
    | '/security'
    | '/service'
    | '/sessions'
    | '/settings'
    | '/tuning'
    | '/vehicle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actuations'
    | '/adapters'
    | '/canbus'
    | '/codes'
    | '/compare'
    | '/data-sources'
    | '/deep-scan'
    | '/emissions'
    | '/ev'
    | '/expert'
    | '/freeze-frame'
    | '/garage'
    | '/health'
    | '/performance'
    | '/reports'
    | '/safety'
    | '/security'
    | '/service'
    | '/sessions'
    | '/settings'
    | '/tuning'
    | '/vehicle'
  id:
    | '__root__'
    | '/'
    | '/actuations'
    | '/adapters'
    | '/canbus'
    | '/codes'
    | '/compare'
    | '/data-sources'
    | '/deep-scan'
    | '/emissions'
    | '/ev'
    | '/expert'
    | '/freeze-frame'
    | '/garage'
    | '/health'
    | '/performance'
    | '/reports'
    | '/safety'
    | '/security'
    | '/service'
    | '/sessions'
    | '/settings'
    | '/tuning'
    | '/vehicle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActuationsRoute: typeof ActuationsRoute
  AdaptersRoute: typeof AdaptersRoute
  CanbusRoute: typeof CanbusRoute
  CodesRoute: typeof CodesRoute
  CompareRoute: typeof CompareRoute
  DataSourcesRoute: typeof DataSourcesRoute
  DeepScanRoute: typeof DeepScanRoute
  EmissionsRoute: typeof EmissionsRoute
  EvRoute: typeof EvRoute
  ExpertRoute: typeof ExpertRoute
  FreezeFrameRoute: typeof FreezeFrameRoute
  GarageRoute: typeof GarageRoute
  HealthRoute: typeof HealthRoute
  PerformanceRoute: typeof PerformanceRoute
  ReportsRoute: typeof ReportsRoute
  SafetyRoute: typeof SafetyRoute
  SecurityRoute: typeof SecurityRoute
  ServiceRoute: typeof ServiceRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  TuningRoute: typeof TuningRoute
  VehicleRoute: typeof VehicleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actuations': {
      id: '/actuations'
      path: '/actuations'
      fullPath: '/actuations'
      preLoaderRoute: typeof ActuationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adapters': {
      id: '/adapters'
      path: '/adapters'
      fullPath: '/adapters'
      preLoaderRoute: typeof AdaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canbus': {
      id: '/canbus'
      path: '/canbus'
      fullPath: '/canbus'
      preLoaderRoute: typeof CanbusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codes': {
      id: '/codes'
      path: '/codes'
      fullPath: '/codes'
      preLoaderRoute: typeof CodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep-scan': {
      id: '/deep-scan'
      path: '/deep-scan'
      fullPath: '/deep-scan'
      preLoaderRoute: typeof DeepScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emissions': {
      id: '/emissions'
      path: '/emissions'
      fullPath: '/emissions'
      preLoaderRoute: typeof EmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ev': {
      id: '/ev'
      path: '/ev'
      fullPath: '/ev'
      preLoaderRoute: typeof EvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert': {
      id: '/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof ExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freeze-frame': {
      id: '/freeze-frame'
      path: '/freeze-frame'
      fullPath: '/freeze-frame'
      preLoaderRoute: typeof FreezeFrameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuning': {
      id: '/tuning'
      path: '/tuning'
      fullPath: '/tuning'
      preLoaderRoute: typeof TuningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle': {
      id: '/vehicle'
      path: '/vehicle'
      fullPath: '/vehicle'
      preLoaderRoute: typeof VehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActuationsRoute: ActuationsRoute,
  AdaptersRoute: AdaptersRoute,
  CanbusRoute: CanbusRoute,
  CodesRoute: CodesRoute,
  CompareRoute: CompareRoute,
  DataSourcesRoute: DataSourcesRoute,
  DeepScanRoute: DeepScanRoute,
  EmissionsRoute: EmissionsRoute,
  EvRoute: EvRoute,
  ExpertRoute: ExpertRoute,
  FreezeFrameRoute: FreezeFrameRoute,
  GarageRoute: GarageRoute,
  HealthRoute: HealthRoute,
  PerformanceRoute: PerformanceRoute,
  ReportsRoute: ReportsRoute,
  SafetyRoute: SafetyRoute,
  SecurityRoute: SecurityRoute,
  ServiceRoute: ServiceRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  TuningRoute: TuningRoute,
  VehicleRoute: VehicleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
